<?php

namespace App\Http\Models;
//By Sao Guang
//update by xiaoming
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;//引入软删除

class ClassInfo extends Model
{
    protected $table = 't_class_info';
    protected $primaryKey = 'class_info_id';

    protected $fillable = ['class_identifier', 'class_name', 'college_info_id'];

    public $timestamps = true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }


    protected function getCollegeInfo()
    {
        return parent::belongsTo('App\Http\Models\CollegeInfo','college_info_id','college_info_id');
    }
}