<?php

namespace App\Http\Models;
//By Sao Guang
//update by xiaoming
use Illuminate\Database\Eloquent\Model;
//引入软删除
use Illuminate\Database\Eloquent\SoftDeletes;

class ClassInfo extends Model
{
    //当向数据库中增加新的学院时，学院的名字写在这个模型
//    const nameCollege = 0;  //待定义学院
    const computerCollege = 1;  //计算机学院

    protected $table = 't_class_info';

    protected $primaryKey = 'class_info_id';

    use SoftDeletes;//软删除
    protected $dates=['delete_at'];

    protected $fillable = ['class_identifier', 'class_name', 'college_info_id'];

    public $timestamps = true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }


    public function college_info_id($ind = null)
    {
        $arr = [
            //名字写这儿
//            self::nameCollege => '待定义学院',
            self::computerCollege => '计算机学院',
        ];

        if ($ind !== null) {
            return array_key_exists($ind, $arr) ? $arr[$ind] : $arr[self::computerCollege];
        }

        return $arr;
    }

}