<?php

namespace App\Http\Models;
//By Sao Guang
//update by xiaoming
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;//引入软删除

class CollegeInfo extends Model
{
    protected $table = 't_college_info';

    protected $primaryKey = 'college_info_id';

    use SoftDeletes;//软删除
    protected $dates=['delete_at'];

    protected $fillable = ['college_identifier', 'college_name', 'college_info_id'];

    public $timestamps = true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }

}