<?php
/*
namespace App\Http\Models;
//By Sao Guang
//update by XIn
use Illuminate\Database\Eloquent\Model;

class MajorInfo extends Model
{
    protected $table = 't_major_info';

    protected $primaryKey = 'major_info_id';

    public $timestamps = true;

    protected function getDateFormat()
    {
        return time();
    }

    protected function asDateTime($value)
    {
        return $value;
    }
}*/


namespace App\Http\Models;
//By Xin
use Illuminate\Database\Eloquent\Model;


class MajorInfo extends Model
{
    protected $table = 't_major_info';

    protected $primaryKey = 'major_info_id';

//    use SoftDeletes;//软删除
//    protected $dates=['delete_at'];

    protected $fillable = ['major_identifier','major_name', 'college_info_id'];

    public $timestamps = true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }

    protected function getCollegeInfo()
    {
        return parent::belongsTo('App\Http\Models\CollegeInfo','college_info_id','college_info_id');
    }



}