<?php

namespace App\Http\Models;
//By Sao Guang
use Illuminate\Database\Eloquent\Model;
//引入软删除
use Illuminate\Database\Eloquent\SoftDeletes;

class SectionInfo extends Model
{
    protected $table = 't_section_info';

    protected $primaryKey = 'section_info_id';

    use SoftDeletes;//软删除
    protected $dates=['delete_at'];

    protected $fillable = ['section_name', 'college_info_id'];

    public $timestamps = true;

    protected function getDateFormat()
    {
        return parent::getDateFormat(); // TODO: Change the autogenerated stub
    }

    protected function asDateTime($value)
    {
        return parent::asDateTime($value); // TODO: Change the autogenerated stub
    }


    protected function getCollegeInfo()
    {
        return parent::belongsTo('App\Http\Models\CollegeInfo','college_info_id','college_info_id');
    }

}